language: go
go:
- '1.10'
before_install:
  - go get github.com/mitchellh/gox
install:
  - # skip
script:
  - go get -t -v ./...
  - go test -v -race ./...
  - if [ -n "$TRAVIS_TAG" ]; then gox -os="linux darwin" -arch="amd64" -output="leader.." -ldflags "-X main.Rev=`git rev-parse --short HEAD`" -verbose ./...; fi
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: "a63rUvww1wHco58Fw30NKKrvS9eLAiUm74sTjD68jsYjHsT++Hdrl/En/Sggh+++bENVpcGKbta5n+koWOmoD5eZipvtpY9AYCOjhWLSfcrLpPu3sPt1w743DrgPbUdzO+ix/WARhXfoA0H6IH1Vq1r5OdQ4oeuxsrs9Ys0LfaYu3NYU7r8SeqQO842BejkCiADxmrLrL3FDr7xdKZEJpj3gk6g56/23g/CSYgbLHC7OoNLW3O5b8HbTgnwS3H+YYHbgRZ1a6GdaXJ5YVZ/KrnlQzUn42cFp5tPXTKYFSK1Azbgmz96mWo1oZxoHTNK5Z7pV3MKmw+zL/NyWLCq57WFWItBhQAWMrQoonvdoZ04PqT7lJjmGcs/rCYRBYlS1gGwUzUw0onBgEFM7JjfTZ5mzt+ow+AKKdIja3EBjmXj5DnnlHpSQCtAAmk2TT65H6qFGUbArfDCmyYwoo7OZxQQeME6QD4+gelBxGvdqSrwM6exE4K8YxvLmrAUOOGXuG8zSZZYY0Km9864RrqmEpzceJiIMyXq9hMhWin6z3PEb2Mh5Ll1d57qOT1scAgfWdmAMzR2zCGAWnyFphBKz8QU2GoBW4EmnPV0XxWwKdQh/prgku+7fLX4wlKNxbr/lGEVVCGpezgrLnztalkFVjpeVIzUZ8fJH6kxEX2ulmak="
  file:
    - leader.linux.amd64
    - leader.darwin.amd64
  on:
    repo: dhamidi/leader
    tags: true
