language: go
go:
- '1.10'
before_install:
- go get github.com/mitchellh/gox
install:
- # skip
script:
- go get -t -v ./...
- go test -v -race ./...
- if [ -n "$TRAVIS_TAG" ]; then gox -os="linux darwin" -arch="amd64" -output="leader.." -ldflags "-X main.Rev=`git rev-parse --short HEAD`" -verbose ./...; fi
deploy:
  provider: releases
  api_key:
    secure: D9M8SwkAGCWamL81sdOL5OsBb7bUgTxXhRjm3CqYsKUmEMzNFyZpFIR7xqIehzs6gGcTvCXkrPjoaD1iTCE0YyOaFNZEX+7pPH/foceWmA4e5ctY9coubReThsQhlqXrPRba2/MCdxqysLVZnbZBblx2ndEh1FqdyuD2KtWVwV+XO2zSkGaPUwvpP0ZSCgF6G2Nt9S1/uUH7GL6YBttBQdT5ce7rvwxb7NhrSCamivaUJJz33G44OkuEhh2Oi1u4+GLWGHiEBF2S435rHJYKomxByxxBcUkOnvrrXi+P4ZCm/C6HaO+4wLoy0XXsYN8VzYObHBWkLFrXWwLA5b9rm6Rzu6zFiXus9yV9ZCncZHX2JqoMkGVE/qr/VtUi8E0DDuso9ugoaod3GmXrYTZnONwJMXtTJDnmTJUIJ0f5tFwlBFgxdek41BYevR2+WQ8JOa6Ei4BIbz7Q2lASEpV2pYPKVYpqhs2Ggk8EoZcENjTVFQxfQThv6Tz6fy5QRQ/DIyEOHjZZnTPgfI4oz933UPKApiBn5xcLlmJ0/55kRzelrzVtrYe0+66NJNlGAh02JzbD4GqB+mLvDrQT88EwgN6FWbWho6QMlzhvgqb9SH1Kf4cdpt6EzDGqV4atizSrYUsYJNuQWSGg4b5wEphV9WJRtRG6ycY7KQ1U29u3F0w=
  skip_cleanup: true
  file:
    - leader.linux.amd64
    - leader.darwin.amd64
  on:
    repo: dhamidi/leader
